/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package usindh;

/**
 *
 * @author SAIF ALI
 */
public class FacultyFrame extends javax.swing.JFrame {

    /**
     * Creates new form FacultyFrame
     */
    public FacultyFrame() {
        initComponents();
        
        java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
        
        getFaculty();
    }
    
    private void getFaculty(){
        try{          
            
              
            
            java.util.Vector v=DatabaseManager.getFaculty();
            this.facultyList.setListData(v);
            
            facultyLabel.setText("FACULTIES:"+v.size());
        }catch(Exception e){
           e.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }
//end getFaculty()
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        facIdText = new javax.swing.JTextField();
        facNameText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        facultyList = new javax.swing.JList();
        facultyLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("FACULTY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 0, 300, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FACULTY ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 190, 160, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("FACULTY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 250, 140, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("REMARKS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 330, 160, 29);

        facIdText.setEditable(false);
        facIdText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(facIdText);
        facIdText.setBounds(580, 190, 90, 30);

        facNameText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(facNameText);
        facNameText.setBounds(580, 250, 490, 30);

        remarksText.setColumns(20);
        remarksText.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        remarksText.setRows(5);
        jScrollPane1.setViewportView(remarksText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(520, 370, 380, 230);

        facultyList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        facultyList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                facultyListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(facultyList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1090, 210, 430, 420);

        facultyLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        facultyLabel.setText("FACULTIES");
        getContentPane().add(facultyLabel);
        facultyLabel.setBounds(1190, 160, 200, 29);

        addButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(470, 661, 130, 40);

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(620, 661, 140, 40);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(770, 660, 170, 40);

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(950, 660, 200, 40);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(1160, 660, 320, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
      
        FacultyBean bean=(FacultyBean)this.facultyList.getSelectedValue();
        if(bean==null)return;
        
        try{          
            int rows=DatabaseManager.deleteFaculty(bean.getFacId());
            javax.swing.JOptionPane.showMessageDialog(this, rows+" Records Removed.");
            getFaculty(); 
            
                        
         this.facIdText.setText("");
        this.facNameText.setText("");
        this.remarksText.setText("");
        }catch(Exception e){
           e.printStackTrace();
           javax.swing.JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
           this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void facultyListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_facultyListValueChanged
        FacultyBean bean=(FacultyBean)this.facultyList.getSelectedValue();
        if(bean==null)return;
        
        this.facIdText.setText(""+bean.getFacId());
        this.facNameText.setText(bean.getFacName());
        this.remarksText.setText(bean.getRemarks());
    }//GEN-LAST:event_facultyListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String facName=facNameText.getText();
        String remarks=remarksText.getText();
        
        try{
            DatabaseManager.addFaculty(facName, remarks);
            
            javax.swing.JOptionPane.showMessageDialog(this,"Record Added");
            getFaculty();
            
        this.facIdText.setText("");
        this.facNameText.setText("");
        this.remarksText.setText("");
            
            
        
        }
        
        catch(Exception e){
        e.printStackTrace();
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
        int id=Integer.parseInt(facIdText.getText());
        String facName=facNameText.getText();
        String remarks=remarksText.getText();
        try{
            
            DatabaseManager.updateFaculty(id, facName, remarks);
            
            getFaculty();

            
            javax.swing.JOptionPane.showMessageDialog(this,"Record Updated");
            
                        
         this.facIdText.setText("");
        this.facNameText.setText("");
        this.remarksText.setText("");
        
        }
        
        catch(Exception e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        
        this.facIdText.setText("");
        this.facNameText.setText("");
        this.remarksText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField facIdText;
    private javax.swing.JTextField facNameText;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JList facultyList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea remarksText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
