package usindh;

import java.awt.Color;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAIF ALI
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        java.awt.Container con=this.getContentPane();
        con.setBackground(Color.blue);
        
        java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facultyButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMISSION SYSTEM, UNIVERSITY OF SINDH, JAMSHORO");
        setBounds(new java.awt.Rectangle(0, 0, 600, 600));
        getContentPane().setLayout(null);

        facultyButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        facultyButton.setText("FACULTY");
        facultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyButton);
        facultyButton.setBounds(520, 140, 190, 31);

        departmentButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        departmentButton.setText("DEPARTMENT");
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmentButton);
        departmentButton.setBounds(520, 190, 190, 31);

        programButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        programButton.setText("PROGRAM");
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });
        getContentPane().add(programButton);
        programButton.setBounds(520, 230, 190, 31);

        batchButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        batchButton.setText("BATCH");
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchButton);
        batchButton.setBounds(520, 270, 190, 31);

        studentButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studentButton.setText("STUDENT");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton);
        studentButton.setBounds(520, 310, 190, 31);

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(520, 350, 190, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButtonActionPerformed
        // TODO add your handling code here:
        FacultyFrame win=new FacultyFrame();
        win.show();
    }//GEN-LAST:event_facultyButtonActionPerformed

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        // TODO add your handling code here:
        
        DepartmentFrame win=new DepartmentFrame();
        
        win.show();
       
   
    }//GEN-LAST:event_departmentButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        // TODO add your handling code here:
        ProgramFrame win=new ProgramFrame();
        win.show();

    }//GEN-LAST:event_programButtonActionPerformed

  
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        // TODO add your handling code here:
        
        BatchFrame win=new BatchFrame();
        win.show();
        
    }//GEN-LAST:event_batchButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
        
        StudentFrame win=new StudentFrame();
        
        win.show();
    }//GEN-LAST:event_studentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                new MainFrame().setVisible(true);
    }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batchButton;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton facultyButton;
    private javax.swing.JButton programButton;
    private javax.swing.JButton studentButton;
    // End of variables declaration//GEN-END:variables
}
