/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package usindh;

import java.util.*;

/**
 *
 * @author SAIF ALI
 */
public class ProgramFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProgramFrame
     */
    public ProgramFrame() {
        initComponents();
        java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
        
        getProgram();

    }
    
   private void  getProgram(){
       
       
       try{
            Vector <FacultyBean> faculty=DatabaseManager.getFaculty();
            
            for(FacultyBean bean:faculty){
            
                this.facCombo.addItem(bean);
            }
            
            
             DepartmentBean dbean=(DepartmentBean)this.deptCombo.getSelectedItem();
             
             if(dbean==null) return;
            
            Vector <ProgramBean>  v=DatabaseManager.getProgram(dbean.getDeptId());
            
                
           this.progListText.setListData(v);
            
           progList.setText("PROGRAMS:"+v.size());
            
  
       
       }
       
       catch(Exception e){
       
            e.printStackTrace();
            
            javax.swing.JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
            
       }
   
   
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        heading = new javax.swing.JLabel();
        facCombo = new javax.swing.JComboBox();
        deptCombo = new javax.swing.JComboBox();
        facName = new javax.swing.JLabel();
        dptName = new javax.swing.JLabel();
        progID = new javax.swing.JLabel();
        progName = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        remarks = new javax.swing.JLabel();
        progList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksText = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        progIDText = new javax.swing.JTextField();
        progNameText = new javax.swing.JTextField();
        durationText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        progListText = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        heading.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        heading.setText("PROGRAMS");
        getContentPane().add(heading);
        heading.setBounds(690, 30, 410, 70);

        facCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        facCombo.setToolTipText("");
        facCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facComboActionPerformed(evt);
            }
        });
        getContentPane().add(facCombo);
        facCombo.setBounds(760, 180, 260, 40);

        deptCombo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deptCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptComboActionPerformed(evt);
            }
        });
        getContentPane().add(deptCombo);
        deptCombo.setBounds(760, 240, 250, 30);

        facName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        facName.setText("FACULTY");
        getContentPane().add(facName);
        facName.setBounds(570, 180, 140, 29);

        dptName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dptName.setText("DEPARTMENT");
        getContentPane().add(dptName);
        dptName.setBounds(570, 240, 210, 29);

        progID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progID.setText("PROGRAMS ID");
        getContentPane().add(progID);
        progID.setBounds(570, 310, 200, 29);

        progName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progName.setText("PROGRAM");
        getContentPane().add(progName);
        progName.setBounds(570, 370, 220, 29);

        duration.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        duration.setText("DURATION IN SEMESTER");
        getContentPane().add(duration);
        duration.setBounds(570, 430, 330, 29);

        remarks.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        remarks.setText("REMARKS");
        getContentPane().add(remarks);
        remarks.setBounds(570, 510, 180, 29);

        progList.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progList.setText("PROGRAMS");
        getContentPane().add(progList);
        progList.setBounds(1180, 170, 170, 29);

        remarksText.setColumns(20);
        remarksText.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        remarksText.setRows(5);
        jScrollPane1.setViewportView(remarksText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(690, 540, 320, 150);

        addButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(560, 730, 140, 40);

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(730, 730, 150, 40);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(900, 730, 130, 40);

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(1050, 730, 190, 40);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(1260, 730, 190, 40);

        progIDText.setEditable(false);
        progIDText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(progIDText);
        progIDText.setBounds(770, 300, 130, 40);

        progNameText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(progNameText);
        progNameText.setBounds(770, 370, 270, 40);

        durationText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(durationText);
        durationText.setBounds(900, 430, 130, 30);

        progListText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        progListText.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                progListTextValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(progListText);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(1120, 220, 320, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facComboActionPerformed
        // TODO add your handling code here:
        
         FacultyBean bean=(FacultyBean)this.facCombo.getSelectedItem();
         if(bean==null) return;
        try{
           deptCombo.removeAllItems();
             
             
            Vector <DepartmentBean> department=DatabaseManager.getDepartment(bean.getFacId());
            
            for(DepartmentBean dp:department){
                
                this.deptCombo.addItem(dp);
            }
            
            
            getProgram();
            
           
   
           
        }
        
        catch(Exception e){
            
            e.printStackTrace();
            
            javax.swing.JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
            
        
        }
        
        
    }//GEN-LAST:event_facComboActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int progID=Integer.parseInt(progIDText.getText());
        String progName=progNameText.getText();
        int duration=Integer.parseInt(durationText.getText());
        String remarks=remarksText.getText();
        
        
        try{
                DatabaseManager.updateProgram(progID, progName, duration, remarks);
                
                javax.swing.JOptionPane.showMessageDialog(this,"Recorded Updated");
                
              
                
        progIDText.setText("");
        progNameText.setText("");
        durationText.setText("");
        remarksText.setText("");
        
          getProgram();
        
                
        }
        
      
        
        
        
        
        catch(Exception e){
            e.printStackTrace();
            
            javax.swing.JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
            
        }
        
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deptComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptComboActionPerformed
        // TODO add your handling code here:
        try{
         
            
           
         
            
  
            getProgram();
            
            
            
        }
        catch(Exception e){
        e.printStackTrace();
        
        javax.swing.JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
        }
            
    }//GEN-LAST:event_deptComboActionPerformed

    private void progListTextValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_progListTextValueChanged
        // TODO add your handling code here:
        
       ProgramBean bean=(ProgramBean) this.progListText.getSelectedValue();
       
       if(bean==null)return;
       
       progIDText.setText(""+bean.getProgId());
       progNameText.setText(bean.getProgName());
       durationText.setText(""+bean.getDurationInSemester());
       remarksText.setText(bean.getRemarks());
       
        getProgram();
        
        
    }//GEN-LAST:event_progListTextValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try{
        
        
        String progName=progNameText.getText();
        int duration=Integer.parseInt(durationText.getText());
        String remarks=remarksText.getText();
        
        DepartmentBean bean=(DepartmentBean) this.deptCombo.getSelectedItem();
        
        DatabaseManager.addPrograms(bean.getDeptId(), progName, duration, remarks);
        
        javax.swing.JOptionPane.showMessageDialog(this,"Recorded Added");
        
       
        
        progIDText.setText("");
        progNameText.setText("");
        durationText.setText("");
        remarksText.setText("");
        
        getProgram();
        
        }
        
        catch(Exception e){
    
                e.printStackTrace();
                
                javax.swing.JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                
    }
        
        
        
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        
        this.progIDText.setText("");
        progNameText.setText("");
        durationText.setText("");
        remarksText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
       
        
       int id=Integer.parseInt(progIDText.getText());
        
        try{
            
           // int rows=DatabaseManager.deleteProgram(bean.getProgId());
            
            DatabaseManager.deleteProgram(id);
            
            javax.swing.JOptionPane.showMessageDialog(this," Deleted");
            
            getProgram();
            
            
        progIDText.setText("");
        progNameText.setText("");
        durationText.setText("");
        remarksText.setText("");
        
        }
        
        catch(Exception e){
        e.printStackTrace();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Error: "+e.getMessage());
        
        
        
        
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox deptCombo;
    private javax.swing.JLabel dptName;
    private javax.swing.JLabel duration;
    private javax.swing.JTextField durationText;
    private javax.swing.JComboBox facCombo;
    private javax.swing.JLabel facName;
    private javax.swing.JLabel heading;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel progID;
    private javax.swing.JTextField progIDText;
    private javax.swing.JLabel progList;
    private javax.swing.JList progListText;
    private javax.swing.JLabel progName;
    private javax.swing.JTextField progNameText;
    private javax.swing.JLabel remarks;
    private javax.swing.JTextArea remarksText;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
